### ISSUE TITLE
"The PK Girl" doesn't run in v5 nor v4 on Windows 10.

### ISSUE THREAD

**Issue by SabinStargem** [jcwild/ADRIFT-5#13]
When I try to run the game, the runner takes a couple minutes and then throws out an error.  Here it is for v5.   I originally tried v4 since that is what PK Girl was intended for, but that also seems to have a similar problem.  The PK Girl worked on prior Windows.

>    at ADRIFT.frmError..ctor(String sErrorMessage, Exception ex)
   at ADRIFT.SharedModule.ErrMsg(String sMessage, Exception ex)
   at ADRIFT.FileIO.LoadOlder(Double v)
   at ADRIFT.FileIO.LoadFile(String sFilename, FileTypeEnum eFileType, LoadWhatEnum eLoadWhat, Boolean bLibrary, DateTime dtAdvDate, clsGameState& state, Int64 lOffset, Boolean bSilentError)
   at ADRIFT.RunnerSession.OpenAdventure(String sFilename, Boolean bSilentError)
   at ADRIFT.frmRunner.frmRunner_Shown(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnShown(EventArgs e)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at ADRIFT.frmRunner.Main()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at R.P.Main(String[] args)

**Comment by kpeamon** [comment]
A comment from another Adrift user: For me, on Windows 10 Home it works both in Adrift 4 and Adrift 5, though the game is not completable in Adrift 5 because of low compatibility with Adrift 4 games in V5. Also, make sure you have the standard library ticked in the Adrift 5 Developer, otherwise Adrift 5 Runner won't run Adrift 4 games.

**Comment by SabinStargem** [comment]
It is my assumption that Adrift 5's error log is more informative than what v4 gives when it fails to load.  "Error loading adventure - [input past end of file,62,8]

**Comment by SabinStargem** [comment]
I figured out the issue:  Locale.  Right now I am using Japanese locale, because a particular game can't run when the actual Locale is set to English.  I am using Locale Emulator to run Adrift v4 in English locale.  Funnily enough, the music works.  On Win7, I wasn't getting music.
